// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn903hBKKQr5uGyMInTSft5plRN1myCX4',
    appId: '1:1075780415515:web:983bb35094e72897bac8be',
    messagingSenderId: '1075780415515',
    projectId: 'flutter-app-learning-73279',
    authDomain: 'flutter-app-learning-73279.firebaseapp.com',
    storageBucket: 'flutter-app-learning-73279.appspot.com',
    measurementId: 'G-KRP89FXQQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbTFeS3mA7N4g27W7lzlIj0IaDUuJnBmM',
    appId: '1:1075780415515:android:a746620e06c4f722bac8be',
    messagingSenderId: '1075780415515',
    projectId: 'flutter-app-learning-73279',
    storageBucket: 'flutter-app-learning-73279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylvGjxFfE1FURGWRSviKqe1RfyRG7I5k',
    appId: '1:1075780415515:ios:3beb2cbb1aeed1b4bac8be',
    messagingSenderId: '1075780415515',
    projectId: 'flutter-app-learning-73279',
    storageBucket: 'flutter-app-learning-73279.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDylvGjxFfE1FURGWRSviKqe1RfyRG7I5k',
    appId: '1:1075780415515:ios:95d9d306bd49cee7bac8be',
    messagingSenderId: '1075780415515',
    projectId: 'flutter-app-learning-73279',
    storageBucket: 'flutter-app-learning-73279.appspot.com',
    iosBundleId: 'com.example.pushNotificationApp.RunnerTests',
  );
}
